### ISSUE TITLE
Need additional option to don't create a queue for RabbitMq connection process

### ISSUE THREAD

**Issue by Konstantin060290** [BEagle1984/silverback#236]
If you don't have an permittion to create a queue (Configure permission) you will receive a connection error: 

EventName=Silverback.Integration_ConsumerConnectError RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=403, text='ACCESS_REFUSED - access to queue 'dummy' in vhost '/' refused for user 'someUser'', classId=50, methodId=10
at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
at RabbitMQ.Client.Impl.ModelBase.QueueDeclare(String queue, Boolean passive, Boolean durable, Boolean exclusive, Boolean autoDelete, IDictionary`2 arguments)
at RabbitMQ.Client.Impl.ModelBase.QueueDeclare(String queue, Boolean durable, Boolean exclusive, Boolean autoDelete, IDictionary`2 arguments)
at RabbitMQ.Client.Impl.AutorecoveringModel.QueueDeclare(String queue, Boolean durable, Boolean exclusive, Boolean autoDelete, IDictionary`2 arguments)
at Silverback.Messaging.Broker.Rabbit.RabbitConnectionFactory.GetChannel(RabbitConsumerEndpoint endpoint)
at Silverback.Messaging.Broker.RabbitConsumer.ConnectCoreAsync()
at Silverback.Messaging.Broker.Consumer.ConnectAndStartAsync()

So it will be cool to have an option to create or not create a queue in connection process for RabbitMq.

**Comment by BEagle1984** [comment]
Thank you for raising this issue. Just a heads-up that RabbitMQ support will be deprecated in Silverback v5. You can find more details and the reasoning in the discussion here: https://github.com/BEagle1984/silverback/discussions/237.

Contributions are welcome if someone wants to take over maintaining it!

**Comment by BEagle1984** [comment]
Closing because RabbitMQ won't be supported anymore.
