### ISSUE TITLE
Improve error message if connection of consumer fails

### ISSUE THREAD

**Issue by msallin** [BEagle1984/silverback#53]
Hi Sergio

I've the situation were there is an application which has two consumers for two topics. Due to a authorization failure they cannot connect. I know that neither of both consumers can connect. However, this can not be inferred by looking at the log message.

```
  | 2020-01-08 18:58:19.910 loglevel="Information" sourceContext="Silverback.Messaging.Broker.KafkaBroker"  message="Creating new consumer for endpoint Topic1." exception="" {}
-- | --

  | 2020-01-08 18:58:19.932 loglevel="Information" sourceContext="Silverback.Messaging.Broker.KafkaBroker"  message="Creating new consumer for endpoint Topic2." exception="" {}
  | 2020-01-08 18:58:20.108 loglevel="Information" sourceContext="Post.SendingDataSystem.Service.Startup"  message="Application started." exception="" {}

  | 2020-01-08 18:58:21.034 loglevel="Warning" sourceContext="Silverback.Messaging.Broker.KafkaConsumer"  message="KafkaException occurred. The consumer will try to recover." exception="Confluent.Kafka.ConsumeException: Broker: Group authorization failed
  | at Confluent.Kafka.Consumer`2.ConsumeImpl[K,V](Int32 millisecondsTimeout, IDeserializer`1 keyDeserializer, IDeserializer`1 valueDeserializer)
  | at Confluent.Kafka.Consumer`2.Consume(CancellationToken cancellationToken)
  | at Silverback.Messaging.Broker.InnerConsumerWrapper.ReceiveMessage()
  | at Silverback.Messaging.Broker.InnerConsumerWrapper.Consume()
  | " {}

  | 2020-01-08 18:58:21.033 loglevel="Warning" sourceContext="Silverback.Messaging.Broker.KafkaConsumer"  message="KafkaException occurred. The consumer will try to recover." exception="Confluent.Kafka.ConsumeException: Broker: Group authorization failed
  | at Confluent.Kafka.Consumer`2.ConsumeImpl[K,V](Int32 millisecondsTimeout, IDeserializer`1 keyDeserializer, IDeserializer`1 valueDeserializer)
  | at Confluent.Kafka.Consumer`2.Consume(CancellationToken cancellationToken)
  | at Silverback.Messaging.Broker.InnerConsumerWrapper.ReceiveMessage()
  | at Silverback.Messaging.Broker.InnerConsumerWrapper.Consume()
  | " {}
```

Is it possible to include this information in the log statement?

**Comment by BEagle1984** [comment]
Would it be enough to add the topic/endpoint name to the log message?

**Comment by msallin** [comment]
Yes, thats exactly what I would like to have! I can create PR, if you shortly advise my where to apply the changes.

**Comment by BEagle1984** [comment]
Since I was at it, I also added the topic name to the error messages.

```
[12:48:22 ERR] Error in Kafka consumer: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: No connection could be made because the target machine actively refused it... (after 3001ms in state CONNECT) (topic(s): silverback-examples-events)  (null)
[12:48:22 ERR] Error in Kafka consumer: 1/1 brokers are down (topic(s): silverback-examples-events)  (null)
```

Is this enough?

**Comment by msallin** [comment]
Thats great!
